# Generated by Django 3.1.3 on 2020-12-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201210_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedvacancies',
            old_name='aspirant',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='companyrating',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.RenameField(
            model_name='favoritevacancies',
            old_name='aspirant',
            new_name='user',
        ),
        migrations.AddField(
            model_name='companyrating',
            name='atmosphere',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='conditions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='interesting_job',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='reputation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
