# Generated by Django 3.1.3 on 2020-12-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('user', '0002_employeerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerating',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='aspirant',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='main_industry',
        ),
        migrations.AddField(
            model_name='employeerating',
            name='communicability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='competence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='effectiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='hard_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeerating',
            name='responsibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfileIndustries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.industry')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
