# Generated by Django 3.1.3 on 2021-01-05 14:31

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201227_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='images/users/default-avatar.png', upload_to=user.models.upload_avatar),
        ),
    ]
