# Generated by Django 3.1.3 on 2021-02-03 11:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210105_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_aspirant',
            field=models.BooleanField(default=False, verbose_name='aspirant status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_contact_person',
            field=models.BooleanField(default=False, verbose_name='contact person status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='images/users/default-avatar.png', null=True, upload_to=user.models.upload_avatar),
        ),
    ]
