# Generated by Django 3.2.1 on 2021-05-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_aspirant',
        ),
    ]
