# Generated by Django 3.2.1 on 2021-05-12 12:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customuser_is_aspirant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='images/users/user.svg', null=True, upload_to=user.models.upload_avatar),
        ),
    ]
